server:
  port: 80
  
spring:
  application:
    name: microservice-consumer #这个很重要，这在以后的服务与服务之间相互调用一般都是根据这个name
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

eureka:
  client:
    registerWithEureka: true # 服务注册开关
    fetchRegistry: true # 服务发现开关
    serviceUrl: # 注册到哪一个Eureka Server服务注册中心，多个中间用逗号分隔
      defaultZone: http://localhost:6001/eureka,http://localhost:6002/eureka
  instance:
    instanceId: ${spring.application.name}:${server.port} # 等价于microservice-provider:8001
    prefer-ip-address: true #访问路径就会显示成IP地址


microservice-provider:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule
    
#  暴露触发消息总线的地址
management:
  endpoints:
    web:
      exposure:
        include: bus-refresh